### PR TITLE
Updates API descriptions in both states & us daily

### LINKED ISSUE #63: Increase fields are incorrectly marked as deprecated
deathIncrease
hospitalizedIncrease
positiveIncrease
totalTestResultsIncrease

**are not** deprecated

negativeIncrease **is** deprecated.

### LINKED ISSUE #67: Update API documentation

### PR DESCRIPTION
**Pull request by amandafrench**
Fixes #67 & Fixes #63 — document of origin is "the loved child has many names" sheet in #data-documentation channel

### CODE REVIEW

**Comment by amandafrench** [comment]
By the way, is it possible to do Markdown links in the API field descriptions? I did put a little Markdown formatting to *format* references to other field names but with that it doesn't matter if it gets converted to formatting or not. I suppose I could put in unlinked URLs if need be but I don't know that it's worth it.

**Comment by kevee** [comment]
Hi, @amandafrench! Some thoughts:

1. Yes, add markdown all you'd like to the definitions. I'll add support to the API page for it now.
2. These definitions will also need to go into `states.js` - I know they are the same, but they are technically two different API sources with slightly different datasets.

**Comment by amandafrench** [comment]
FYI this is also related to #63 -- at that time the xIncrease fields were undeprecated in states daily but not also in US daily

**Comment by amandafrench** [comment]
@kevee I did put the definitions in both `states.js` and `us.js` -- it was only undeprecating the increase fields that went only into `us.js` because it hadn't been done before

**Comment by kevee** [comment]
Fixes #63

**Pull request merged**
